---
application:
  name: "pratikproject"
  project: "pratikproject"
  organization: "QoveryCommunity"
routers:
- name: "main-pratikproject"
  routes:
  - application_name: "pratikproject"
    paths:
    - "/*"
