qovery:
  key: jtme9xokl7cc63cp/gb8s60ik4dbbgg4k/hn1rqaq9i2b7ag1x
application:
  name: flask-todo
  project: flask-todo
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-postgresql-3498225
routers:
- name: main
  routes:
  - application_name: flask-todo
    paths:
    - /*
